# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-09 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0002_auto_20181007_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='mata_pelajaran',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mata_pelajaran.MataPelajaran'),
        ),
    ]
